services:
    cca.dc-general.backend_listener.paste_all_handler:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\MultipleHandler\PasteAllHandler
        public: true
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            -   name: kernel.event_listener
                event: dc-general.action
                method: handleEvent

    cca.dc-general.backend_listener.edit_all_handler:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\MultipleHandler\EditAllHandler
        public: true
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            -   name: kernel.event_listener
                event: dc-general.action
                method: handleEvent

    cca.dc-general.backend_listener.override_all_handler:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\MultipleHandler\OverrideAllHandler
        public: true
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            -   name: kernel.event_listener
                event: dc-general.action
                method: handleEvent

    cca.dc-general.backend_listener.select_model_all_handler:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\MultipleHandler\SelectModelAllHandler
        public: true
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            -   name: kernel.event_listener
                event: dc-general.action
                method: handleEvent

    cca.dc-general.backend_listener.select_all_property_handler:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\MultipleHandler\SelectPropertyAllHandler
        public: true
        arguments:
            - "@cca.dc-general.scope-matcher"
            - "@translator"
            - "@cca.translator.contao_translator"
            - "@security.csrf.token_manager"
            - "%contao.csrf_token_name%"
        tags:
            -   name: kernel.event_listener
                event: dc-general.action
                method: handleEvent
