services:
    cca.dc-general.backend_listener.extended_legacy_dca_populator:
        class: ContaoCommunityAlliance\DcGeneral\Contao\Dca\Populator\ExtendedLegacyDcaPopulator
        public: true
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            -   name: kernel.event_listener
                event: dc-general.factory.populate-environment
                method: process
                priority: 100
