dist: xenial

addons:
  apt:
    packages:
      - ant-optional

language: php

php:
    - "7.3"
    - "7.2"
    - "7.1"
    - "7.0"
    - "5.6"

env:
    - CONTAO_VERSION=~3.5.5

before_install:
    - echo "memory_limit = -1" > travis.php.ini && phpenv config-add travis.php.ini

install:
    - echo "memory_limit = -1" > travis.php.ini && phpenv config-add travis.php.ini
    - travis_retry composer self-update && composer --version
    - travis_retry composer require contao/core $CONTAO_VERSION --no-update
    - travis_retry composer update --prefer-dist --dev --no-interaction

script: ant -keep-going

# Hack to make things work again - we can not use a shallow repository.
git:
  depth: 2147483647
