services:
    cca.dc-general.general_listener.tree_enforcing:
        class: ContaoCommunityAlliance\DcGeneral\EventListener\ModelRelationship\TreeEnforcingListener
        public: true
        tags:
            - { name: kernel.event_listener, event: dc-general.model.enforce-relationship, method: process }

    cca.dc-general.general_listener.parent_enforcing:
        class: ContaoCommunityAlliance\DcGeneral\EventListener\ModelRelationship\ParentEnforcingListener
        public: true
        tags:
            - { name: kernel.event_listener, event: dc-general.model.enforce-relationship, method: process }
